### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by m4rkyyyexe** [chlkrisz/marisa#1]
1. Ellopta Patchouli konyveit
2. Ellopta a vesem
3. Hol a bankkartyam
4. Ja varj megvan
5. Geci hova lett rola a penz
6. Wait a minute

**Comment by chlkrisz** [comment]
leszarom jóéjszakát

**Comment by m4rkyyyexe** [comment]
a kurva anyád

**Comment by chlkrisz** [comment]
Te büdös patkány

**Comment by m4rkyyyexe** [comment]
23 eves vagyok

**Comment by chlkrisz** [comment]
vergodjel a foldon
